language: python
dist: xenial

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - pypy3.5-7.0

install:
  - pip install coveralls tox-travis

script:
  - tox -- --cov-append

matrix:
  fast_finish: true
  include:
    - python: "3.6"
      env: TOX_ENV=docs
      script: tox -e $TOX_ENV
    - python: "3.6"
      env: TOX_ENV=flake8
      script: tox -e $TOX_ENV

after_success:
  - coveralls

before_deploy:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then travis_terminate 0; fi'
  - pip install githubrelease
  - pip install --pre autopub
  - autopub check || travis_terminate 0
  - pip install poetry
  - pip install twine
  - git checkout ${TRAVIS_BRANCH}
  - git remote set-url origin https://$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG

deploy:
  provider: script
  script: autopub deploy
  skip_cleanup: true
  on:
    branch: main
    python: "3.7"

env:
  global:
    - PYPI_USERNAME=autopub
    - secure: "O2fzB+zALWG9TOdD45ZnZAh2C8hEKftnEwp0Y8DtnbGh47rJFKMuG/DlbN9VhlywAXeI0p4CaQ+Bpx/hAp9AK1dmFEzKcnyTF+35abrjNHpKxk1o13xZItR5LCXBqA2hpa19TagsdtoZHC3OVbmg2VY3UpocQR5cL+1QHaprwtsl6rfLTQxLM+kO2C2zZluj8mJ4TS3i5wY9ZkRU86GgRQgOo/IP4tftSyXHMYnoiDjfRqq/l3KH4igU8+KzomQH574Wcg4tJ+UO0c3UcuHP99u5NOqYYBQT45R+ybFJbt6ZW+ji2TndIcuF/9fnTFg+vrMc6QVkZOw+fkXe6VH+Hfiw1sgPauY6ZyQZWX+dXT5EcvCoDae3P1pDVzpRB9q1UShF+ZuZagq7jRu+Rcrta8u8A6gNhwfXaz47IUFI8ZLk449nEPTw/zbDk6oRt0bfDVn3dmzoeo8J/TeLBi2MgnaI+SMCh48kPTRT/mEFW/KPdAY+S28p+Jpwlzp1nt5M1STMbn22XJK4/tJaZpGwqv9LGNvsk+aKDFtrubzm0cIa/v+IU/E5rMDccn/SF8ApvrTQBTHiKH0btFN2oSLT8CDhzffDJlzGjfqNIjbRAUb/cqZ80lmM7ufOVWphHW+9no7MIxvJfGi1oSev9sWmHVyAhro+riqnnxTvZXGjY4I="
    - secure: "f1g4QjySDxmPHLzjxn+eCv7IeU7y3CuLzvVxFpl4wbnQsE1O9CKbUmPK2oaBvVSr1MhsjtexKZrwIfJNpEBMK/s4jjKkNjgsuUq0/i2LYB7XzGhWGsOEp5lrux6iQqV5diZOArvRyaVvitoW4xm9U4PPQ/rfTwNcfYjy2ZYAFZQasbzOggQSczrusk7t0NkMuUR1LBSsfdQaarT/R7xmNATnq4KMrDN4jILM1DK2j+svUJ7vqHa+qOyMwz6v0hXK+iyJQzNRsG0i7V1EjhepNikXhX/klDlCy6kXR7WWBuLuURyiEt2yABABqiuwICHw04rr9RjI7o5ObOvrYZVrNsOpUgZnahIxs1evvgx6+GrjEkv0wsuPx9rk+LaMDrOPWbCnUObmqvDXIbw2ltzqk+6BdCX65mKnrG9aQnlHsiqm8htLX7EmY+9DuL/ZgR0Bv1x1x4w1jHyhTWLQMzo2I1UPy1JCIp6bHVmHjnD7gBFSanNLcuT8kr9hcYkwTnXxQmg9h0M0thSjHCOeJ9NFV3NcTmkFMYuBeOiVVs/HxDj39q+iUsuet2Tj4J2OnifQvEkdcN5N9tl0L52VIt0dLoujrU/Kch3w7jDYLmrrSj2JEfZeSDZJiysjbLx2DkWNDIosyWokNud4uYIcerVx7dPZ+HF1NI1S8HwuTHMvsac="
    - TWINE_USERNAME=$PYPI_USERNAME
    - TWINE_PASSWORD=$PYPI_PASSWORD
