[tox]
envlist =
    py{311,312}-django{42,52}
    py313-django52
    docs
    ruff

[testenv]
deps =
    django42: Django>=4.2,<4.3
    django52: Django>=5.2,<5.3
    coverage
    pytest
    pytest-cov
    pytest-django
commands = pytest --cov=elevate --cov-report=xml {posargs}

[gh-actions]
python =
    3.11: py311
    3.12: py312
    3.13: py313

[testenv:docs]
changedir=docs
commands=sphinx-build -W -b html -d _build/doctrees . _build/html
extras = docs

[testenv:ruff]
commands=ruff check elevate tests conftest.py tasks.py {posargs}
deps=ruff
skip_install = true
